export const GET_PDF_DATA = "GET_PDF_DATA";
export const GET_PDF_DATA_SUCCESS = "GET_PDF_DATA_SUCCESS";
export const GET_PDF_DATA_FAILURE = "GET_PDF_DATA_FAILURE";
export const POST_PDF_DATA = "POST_PDF_DATA";
export const POST_PDF_DATA_SUCCESS = "POST_PDF_DATA_SUCCESS";
export const POST_PDF_DATA_FAILURE = "POST_PDF_DATA_FAILURE";
