# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
workflows:
  version: 2
  main:
jobs:
  - build
  - deploy-prod:
      requires:
        - build #alternately this could depend on deploy-dev to have a linear flow instead of split
      filters:
        branches:
          only: circle_ci

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.2

      working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test

      - run: yarn build