import { MODULE_PREFIX } from "./constants";

export const GET_STATUSES_LIST = `${MODULE_PREFIX}_GET_STATUSES_LIST`;
export const GET_STATUSES_LIST_SUCCESS = `${MODULE_PREFIX}_GET_STATUSES_LIST_SUCCESS`;
export const GET_STATUSES_LIST_FAILURE = `${MODULE_PREFIX}_GET_STATUSES_LIST_FAILURE`;

export const GET_REGIONS_LIST = `${MODULE_PREFIX}_GET_REGIONS_LIST`;
export const GET_REGIONS_LIST_SUCCESS = `${MODULE_PREFIX}_GET_REGIONS_LIST_SUCCESS`;
export const GET_REGIONS_LIST_FAILURE = `${MODULE_PREFIX}_GET_REGIONS_LIST_FAILURE`;

export const GET_BUSINESS_UNITS_LIST = `${MODULE_PREFIX}_GET_BUSINESS_UNITS_LIST`;
export const GET_BUSINESS_UNITS_LIST_SUCCESS = `${MODULE_PREFIX}_GET_BUSINESS_UNITS_LIST_SUCCESS`;
export const GET_BUSINESS_UNITS_LIST_FAILURE = `${MODULE_PREFIX}_GET_BUSINESS_UNITS_LIST_FAILURE`;
