export const fieldConstants = {
  RESPONSE_SAVE_REQUEST: "RESPONSE_SAVE_REQUEST",
  RESPONSE_SAVE_SUCCESS: "RESPONSE_SAVE_SUCCESS",
  RESPONSE_SAVE_FAILURE: "RESPONSE_SAVE_FAILURE",

  FIELD_FETCH_EXTRA_REQUEST: "FIELD_FETCH_EXTRA_REQUEST",
  FIELD_FETCH_EXTRA_SUCCESS: "FIELD_FETCH_EXTRA_SUCCESS",
  FIELD_FETCH_EXTRA_FAILURE: "FIELD_FETCH_EXTRA_FAILURE"
};
