export const MODAL_WIDTH = "77vw";
export const WORKFLOW_DETAILS_CONTAINER_PADDING_LEFT = "0";
export const WORKFLOW_DETAILS_CONTAINER_PADDING_RIGHT = "10px";
export const BACK_BUTTON_WIDTH = "70px";
export const BACK_BUTTON_MARGIN_RIGHT = "20px";
export const WORKFLOW_DETAILS_SIDEBAR_WIDTH = "350px";
export const WORKFLOW_DETAILS_SIDEBAR_PADDING = "40px";
