import { MODULE_NAME } from "./constants";

export const GET_STATUSES_LIST = `${MODULE_NAME}_GET_STATUSES_LIST`;
export const GET_STATUSES_LIST_SUCCESS = `${MODULE_NAME}_GET_STATUSES_LIST_SUCCESS`;
export const GET_STATUSES_LIST_FAILURE = `${MODULE_NAME}_GET_STATUSES_LIST_FAILURE`;

export const GET_REGIONS_LIST = `${MODULE_NAME}_GET_REGIONS_LIST`;
export const GET_REGIONS_LIST_SUCCESS = `${MODULE_NAME}_GET_REGIONS_LIST_SUCCESS`;
export const GET_REGIONS_LIST_FAILURE = `${MODULE_NAME}_GET_REGIONS_LIST_FAILURE`;

export const GET_BUSINESS_UNITS_LIST = `${MODULE_NAME}_GET_BUSINESS_UNITS_LIST`;
export const GET_BUSINESS_UNITS_LIST_SUCCESS = `${MODULE_NAME}_GET_BUSINESS_UNITS_LIST_SUCCESS`;
export const GET_BUSINESS_UNITS_LIST_FAILURE = `${MODULE_NAME}_GET_BUSINESS_UNITS_LIST_FAILURE`;

export const GET_ALL_KINDS = `${MODULE_NAME}_GET_ALL_KINDS`;
export const GET_ALL_KINDS_SUCCESS = `${MODULE_NAME}_GET_ALL_KINDS_SUCCESS`;
export const GET_ALL_KINDS_FAILURE = `${MODULE_NAME}_GET_ALL_KINDS_FAILURE`;

export const GET_ALL_ALERTS = `${MODULE_NAME}_GET_ALL_ALERTS`;
export const GET_ALL_ALERTS_SUCCESS = `${MODULE_NAME}_GET_ALL_ALERTS_SUCCESS`;
export const GET_ALL_ALERTS_FAILURE = `${MODULE_NAME}_GET_ALL_ALERTS_FAILURE`;

export const GET_ALL_TASK_QUEUES = `${MODULE_NAME}_GET_ALL_TASK_QUEUES`;
export const GET_ALL_TASK_QUEUES_SUCCESS = `${MODULE_NAME}_GET_ALL_TASK_QUEUES_SUCCESS`;
export const GET_ALL_TASK_QUEUES_FAILURE = `${MODULE_NAME}_GET_ALL_TASK_QUEUES_FAILURE`;
