export const MODULE_NAME = "WORKFLOW_LIST";
export const MY_TASK_FILTER_NAME = "user-step-tag";
export const STATUS_FILTER_NAME = "status";
export const REGION_FILTER_NAME = "region";
export const BUSINESS_UNIT_FILTER_NAME = "business_unit";
export const TASK_QUEUE_FILTER_NAME = "stepgroupdef";
export const ALERTS_FILTER_NAME = "alerts"; // TODO: Add this
export const KIND_FILTER_NAME = "kind";
export const PRIMARY_KEY_SORTING_FILTER_NAME = "ordering";
