export const dunsFieldConstants = {
  //SAVE THE FIRST ANSWER FOR FIELDS
  DUNS_FIELD_REQUEST: "DUNS_FIELD_UPDATE_POST_REQUEST",
  DUNS_FIELD_SUCCESS: "DUNS_FIELD_UPDATE_POST_SUCCESS",
  DUNS_FIELD_FAILURE: "DUNS_FIELD_UPDATE_POST_FAILURE"
};
