export const dunsFieldConstants = {
  //SAVE THE FIRST ANSWER FOR FIELDS
  DUNS_FIELD_REQUEST: "DUNS_FIELD_UPDATE_POST_REQUEST",
  DUNS_FIELD_SUCCESS: "DUNS_FIELD_UPDATE_POST_SUCCESS",
  DUNS_FIELD_FAILURE: "DUNS_FIELD_UPDATE_POST_FAILURE",

  //SELECT DUNS ITEM FROM RESPONSE LIST
  DUNS_SELECT_REQUEST: "DUNS_SELECT_UPDATE_POST_REQUEST",
  DUNS_SELECT_SUCCESS: "DUNS_SELECT_UPDATE_POST_SUCCESS",
  DUNS_SELECT_FAILURE: "DUNS_SELECT_UPDATE_POST_FAILURE"
};
