export const stepPreviewConstants = {
  PREVIEW_STEP_REQUEST: "PREVIEW_STEP_FIELDS_GET_REQUEST",
  PREVIEW_STEP_SUCCESS: "PREVIEW_STEP_FIELDS_GET_SUCCESS",
  PREVIEW_STEP_FAILURE: "PREVIEW_STEP_FIELDS_GET_FAILURE"
};
