export const userConstants = {
  REGISTER_REQUEST: "USERS_REGISTER_REQUEST",
  REGISTER_SUCCESS: "USERS_REGISTER_SUCCESS",
  REGISTER_FAILURE: "USERS_REGISTER_FAILURE",

  LOGIN_REQUEST: "USERS_LOGIN_REQUEST",
  LOGIN_SUCCESS: "USERS_LOGIN_SUCCESS",
  LOGIN_FAILURE: "USERS_LOGIN_FAILURE",

  LOGIN_LINK_REQUEST: "USERS_LOGIN_LINK__REQUEST",
  LOGIN_LINK_SUCCESS: "USERS_LOGIN_LINK_SUCCESS",
  LOGIN_LINK_FAILURE: "USERS_LOGIN_LINK_FAILURE",

  LOGOUT: "USERS_LOGOUT",
  LOGOUT: "USERS_SUCCESS",

  GETALL_REQUEST: "USERS_GETALL_REQUEST",
  GETALL_SUCCESS: "USERS_GETALL_SUCCESS",
  GETALL_FAILURE: "USERS_GETALL_FAILURE",

  GET_REQUEST: "USER_GET_REQUEST",
  GET_SUCCESS: "USER_GET_SUCCESS",
  GET_FAILURE: "USER_GET_FAILURE",

  DELETE_REQUEST: "USERS_DELETE_REQUEST",
  DELETE_SUCCESS: "USERS_DELETE_SUCCESS",
  DELETE_FAILURE: "USERS_DELETE_FAILURE",

  GETME_REQUEST: "ME_GET_REQUEST",
  GETME_SUCCESS: "ME_GET_SUCCESS",
  GETME_FAILURE: "ME_GET_FAILURE"
};
