export const workflowCommentsConstants = {
  GET_COMMENTS_REQUEST: "COMMENTS_GET_REQUEST",
  GET_COMMENTS_SUCCESS: "COMMENTS_GET_SUCCESS",
  GET_COMMENTS_FAILURE: "COMMENTS_GET_FAILURE",

  ADD_COMMENTS_REQUEST: "COMMENTS_SUBMIT_REQUEST",
  ADD_COMMENTS_SUCCESS: "COMMENTS_SUBMIT_SUCCESS",
  ADD_COMMENTS_FAILURE: "COMMENTS_SUBMIT_FAILURE"
};
