export const workflowKindConstants = {
  GETALL_REQUEST: "WORKFLOWKIND_GETALL_REQUEST",
  GETALL_SUCCESS: "WORKFLOWKIND_GETALL_SUCCESS",
  GETALL_FAILURE: "WORKFLOWKIND_GETALL_FAILURE",

  //CONST FOR WORKFLOW GROUP COUNT FOR AGGERATED FILTERS
  GET_COUNT_REQUEST: "WORKFLOW_GROUP_COUNT_GET_REQUEST",
  GET_COUNT_SUCCESS: "WORKFLOW_GROUP_COUNT_GET_SUCCESS",
  GET_COUNT_FAILURE: "WORKFLOW_GROUP_COUNT_GET_FAILURE"

  // DELETE_REQUEST: "WORKFLOW_DELETE_REQUEST",
  // DELETE_SUCCESS: "WORKFLOW_DELETE_SUCCESS",
  // DELETE_FAILURE: "WORKFLOW_DELETE_FAILURE"
};
