export const workflowCreateConstants = {
  CREATE_REQUEST: "WORKFLOW_CREATE_REQUEST",
  CREATE_SUCCESS: "WORKFLOW_CREATE_SUCCESS",
  CREATE_FAILURE: "WORKFLOW_CREATE_FAILURE"

  // DELETE_REQUEST: "WORKFLOW_DELETE_REQUEST",
  // DELETE_SUCCESS: "WORKFLOW_DELETE_SUCCESS",
  // DELETE_FAILURE: "WORKFLOW_DELETE_FAILURE"
};
