export const workflowKindConstants = {
  GETALL_REQUEST: "WORKFLOWKIND_GETALL_REQUEST",
  GETALL_SUCCESS: "WORKFLOWKIND_GETALL_SUCCESS",
  GETALL_FAILURE: "WORKFLOWKIND_GETALL_FAILURE"

  // DELETE_REQUEST: "WORKFLOW_DELETE_REQUEST",
  // DELETE_SUCCESS: "WORKFLOW_DELETE_SUCCESS",
  // DELETE_FAILURE: "WORKFLOW_DELETE_FAILURE"
};
