export const workflowStepConstants = {
  GET_STEPFIELDS_REQUEST: "STEP_FIELDS_GET_REQUEST",
  GET_STEPFIELDS_SUCCESS: "STEP_FIELDS_GET_SUCCESS",
  GET_STEPFIELDS_FAILURE: "STEP_FIELDS_GET_FAILURE",

  SUBMIT_REQUEST: "WORKFLOW_STEP_SUBMIT_REQUEST",
  SUBMIT_SUCCESS: "WORKFLOW_STEP_SUBMIT_SUCCESS",
  SUBMIT_FAILURE: "WORKFLOW_STEP_SUBMIT_FAILURE",

  APPROVE_REQUEST: "WORKFLOW_STEP_APPROVE_REQUEST",
  APPROVE_SUCCESS: "WORKFLOW_STEP_APPROVE_SUCCESS",
  APPROVE_FAILURE: "WORKFLOW_STEP_APPROVE_FAILURE",

  UNDO_REQUEST: "WORKFLOW_STEP_UNDO_REQUEST",
  UNDO_SUCCESS: "WORKFLOW_STEP_UNDO_SUCCESS",
  UNDO_FAILURE: "WORKFLOW_STEP_UNDO_FAILURE"
};
