export const workflowConstants = {
  GETALL_REQUEST: "WORKFLOW_GETALL_REQUEST",
  GETALL_SUCCESS: "WORKFLOW_GETALL_SUCCESS",
  GETALL_FAILURE: "WORKFLOW_GETALL_FAILURE",

  GET_REQUEST: "WORKFLOW_REQUEST",
  GET_SUCCESS: "WORKFLOW_SUCCESS",
  GET_FAILURE: "WORKFLOW_FAILURE",

  SEARCH_REQUEST: "SEARCH_REQUEST",
  SEARCH_SUCCESS: "SEARCH_SUCCESS",
  SEARCH_FAILURE: "SEARCH_FAILURE"

  // DELETE_REQUEST: "WORKFLOW_DELETE_REQUEST",
  // DELETE_SUCCESS: "WORKFLOW_DELETE_SUCCESS",
  // DELETE_FAILURE: "WORKFLOW_DELETE_FAILURE"
};
