export const workflowDetailsConstants = {
  GET_REQUEST: "WORKFLOW_DETAILS_GET_REQUEST",
  GET_SUCCESS: "WORKFLOW_DETAILS_GET_SUCCESS",
  GET_FAILURE: "WORKFLOW_DETAILS_GET_FAILURE",

  GET_STEPGROUPS_REQUEST: "WORKFLOW_DETAILS_STEPGROUP_GET_REQUEST",
  GET_STEPGROUPS_SUCCESS: "WORKFLOW_DETAILS_STEPGROUP_GET_SUCCESS",
  GET_STEPGROUPS_FAILURE: "WORKFLOW_DETAILS_STEPGROUP_GET_FAILURE",

  DELETE_REQUEST: "WORFLOW_DETAILS_DELETE_REQUEST",
  DELETE_SUCCESS: "WORFLOW_DETAILS_DELETE_SUCCESS",
  DELETE_FAILURE: "WORFLOW_DETAILS_DELETE_FAILURE",

  SET_STEP_ID: "SET_CURRENT_STEP_ID",
  REMOVE_STEP_ID: "REMOVE_CURRENT_STEP_ID",
  SET_AS_INVALID_WORKFLOW_DETAILS: "SET_AS_INVALID_WORKFLOW_DETAILS",
  SET_AS_INVALID_STEP_FIELDS: "SET_AS_INVALID_STEP_FIELDS"
};
