export const workflowFieldConstants = {
  //SAVE THE FIRST ANSWER FOR FIELDS
  POST_FIELD_REQUEST: "FIELD_POST_REQUEST",
  POST_FIELD_SUCCESS: "FIELD_POST_SUCCESS",
  POST_FIELD_FAILURE: "FIELD_POST_FAILURE",

  //UPDATE THE FIELD DATA
  PATCH_FIELD_REQUEST: "FIELD_PATCH_REQUEST",
  PATCH_FIELD_SUCCESS: "FIELD_PATCH_SUCCESS",
  PATCH_FIELD_FAILURE: "FIELD_PATCH_FAILURE",

  //FETCH EXTRA (OPTIONS) FOR FIELD
  FETCH_FIELD_EXTRA_REQUEST: "FETCH_FIELD_EXTRA_REQUEST",
  FETCH_FIELD_EXTRA_SUCCESS: "FETCH_FIELD_EXTRA_SUCCESS",
  FETCH_FIELD_EXTRA_FAILURE: "FETCH_FIELD_EXTRA_FAILURE"
};
