export const workflowDetailsConstants = {
  GET_REQUEST: "WORFLOW_DETAILS_GET_REQUEST",
  GET_SUCCESS: "WORFLOW_DETAILS_GET_SUCCESS",
  GET_FAILURE: "WORFLOW_DETAILS_GET_FAILURE",

  DELETE_REQUEST: "WORFLOW_DETAILS_DELETE_REQUEST",
  DELETE_SUCCESS: "WORFLOW_DETAILS_DELETE_SUCCESS",
  DELETE_FAILURE: "WORFLOW_DETAILS_DELETE_FAILURE"
};
