export const workflowDetailsheaderConstants = {
  GET_REQUEST: "WORKFLOW_DETAILS_HEADER_GET_REQUEST",
  GET_SUCCESS: "WORKFLOW_DETAILS_HEADER_GET_SUCCESS",
  GET_FAILURE: "WORKFLOW_DETAILS_HEADER_GET_FAILURE"
};
